version: '2.1'
executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'
orbs:
  maven: circleci/maven@1.3.0

commands:
  build:
    steps:
      - checkout
      - run: mvn clean test
      - maven/process_test_results

jobs:
  build:
    executor: java17
    steps:
      - build
    

workflows:
  maven_test:
    jobs:
      - build
